/*
 * File: app/view/CategoriesPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Etsy.view.CartPanel', {
    extend: 'Ext.Panel',

    config: {
        title: 'Cart',
        iconCls: 'shop1',
        id: 'cartPanel',
        layout: 'card',
        items: [
        
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Your Cart',
                id: 'cartToolbar',
                items: [{
                    xtype: 'button',
                    ui: 'plain', action: 'showNav',width: 60,
                    iconCls: 'list',
    				iconMask: true,
                },
					{xtype: 'spacer'},
					{
	                    xtype: 'button',
	                    id: 'cartPanelSignInButton',
	                    text: 'Sign In'
	                },
					{
	                    xtype: 'button',
	                    id: 'cartPanelSignOutButton',
	                    text: 'Sign Out',
						hidden: true
	                },

                // {
                //                     xtype: 'searchfield',
                //                     id: 'favoritesPanelSearch',
                //                     placeHolder: 'Search Etsy'
                //                 }
				]
            },
			{
				xtype: 'container',
				layout: 'vbox',
				defaults:{
					cls: '',
				},
				items: [
				{
					id: 'cartContent',
					html: 'Please sign in to browse your Etsy cart'
				}
				]
			}
            


        ]
    }

});